#version 450
layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0) uniform samplerCube environmentMap;
layout (binding = 1, rgba16f) uniform writeonly imageCube irradianceMap;

const float PI = 3.14159265359;

void main() {
    ivec3 pos = ivec3(gl_GlobalInvocationID);
    vec2 size = imageSize(irradianceMap).xy;
    if (pos.x >= size.x || pos.y >= size.y) return;

    vec2 uv = (vec2(pos.xy) + 0.5) / size;
    vec2 coords = uv * 2.0 - 1.0;

    vec3 normal;
    if (pos.z == 0) normal = vec3(1.0, -coords.y, -coords.x);
    if (pos.z == 1) normal = vec3(-1.0, -coords.y, coords.x);
    if (pos.z == 2) normal = vec3(coords.x, 1.0, coords.y);
    if (pos.z == 3) normal = vec3(coords.x, -1.0, -coords.y);
    if (pos.z == 4) normal = vec3(coords.x, -coords.y, 1.0);
    if (pos.z == 5) normal = vec3(-coords.x, -coords.y, -1.0);
    normal = normalize(normal);

    vec3 irradiance = vec3(0.0);
    vec3 up = vec3(0.0, 1.0, 0.0);
    vec3 right = normalize(cross(up, normal));
    up = normalize(cross(normal, right));

    float sampleDelta = 0.025;
    float nrSamples = 0.0;
    for (float phi = 0.0; phi < 2.0 * PI; phi += sampleDelta) {
        for (float theta = 0.0; theta < 0.5 * PI; theta += sampleDelta) {
            vec3 tangentSample = vec3(sin(theta) * cos(phi), sin(theta) * sin(phi), cos(theta));
            vec3 sampleVec = tangentSample.x * right + tangentSample.y * up + tangentSample.z * normal;
            irradiance += texture(environmentMap, sampleVec).rgb * cos(theta) * sin(theta);
            nrSamples++;
        }
    }
    irradiance = PI * irradiance * (1.0 / nrSamples);

    imageStore(irradianceMap, pos, vec4(irradiance, 1.0));
}
