#version 450
layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 0) uniform samplerCube environmentMap;
layout (binding = 1, rgba16f) uniform writeonly imageCube prefilteredMap;

layout (push_constant) uniform PushConstants {
    float roughness;
    uint numSamples;
} push;

const float PI = 3.14159265359;

float RadicalInverse_VdC(uint bits) {
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10;
}

vec2 Hammersley(uint i, uint N) {
    return vec2(float(i) / float(N), RadicalInverse_VdC(i));
}

vec3 ImportanceSampleGGX(vec2 Xi, vec3 N, float roughness) {
    float a = roughness * roughness;
    float phi = 2.0 * PI * Xi.x;
    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a * a - 1.0) * Xi.y));
    float sinTheta = sqrt(1.0 - cosTheta * cosTheta);
    vec3 H = vec3(cos(phi) * sinTheta, sin(phi) * sinTheta, cosTheta);
    vec3 up = abs(N.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
    vec3 tangent = normalize(cross(up, N));
    vec3 bitangent = cross(N, tangent);
    return normalize(tangent * H.x + bitangent * H.y + N * H.z);
}

void main() {
    ivec3 pos = ivec3(gl_GlobalInvocationID);
    vec2 size = imageSize(prefilteredMap).xy;
    if (pos.x >= size.x || pos.y >= size.y) return;

    vec2 uv = (vec2(pos.xy) + 0.5) / size;
    vec2 coords = uv * 2.0 - 1.0;

    vec3 normal;
    if (pos.z == 0) normal = vec3(1.0, -coords.y, -coords.x);
    if (pos.z == 1) normal = vec3(-1.0, -coords.y, coords.x);
    if (pos.z == 2) normal = vec3(coords.x, 1.0, coords.y);
    if (pos.z == 3) normal = vec3(coords.x, -1.0, -coords.y);
    if (pos.z == 4) normal = vec3(coords.x, -coords.y, 1.0);
    if (pos.z == 5) normal = vec3(-coords.x, -coords.y, -1.0);
    normal = normalize(normal);

    vec3 N = normal;
    vec3 V = N;

    float totalWeight = 0.0;
    vec3 prefilteredColor = vec3(0.0);
    for (uint i = 0u; i < push.numSamples; ++i) {
        vec2 Xi = Hammersley(i, push.numSamples);
        vec3 H = ImportanceSampleGGX(Xi, N, push.roughness);
        vec3 L = normalize(2.0 * dot(V, H) * H - V);
        float NdotL = max(dot(N, L), 0.0);
        if (NdotL > 0.0) {
            prefilteredColor += texture(environmentMap, L).rgb * NdotL;
            totalWeight += NdotL;
        }
    }
    prefilteredColor = prefilteredColor / totalWeight;

    imageStore(prefilteredMap, pos, vec4(prefilteredColor, 1.0));
}
