[package]
name = "spark-editor"
version.workspace = true
edition.workspace = true

[dependencies]
spark-core = { path = "../spark-core" }
spark-renderer = { path = "../spark-renderer" }
spark-script = { path = "../spark-script" }
spark-math = { path = "../spark-math" }
ash.workspace = true
shaderc.workspace = true
winit.workspace = true
egui.workspace = true
egui-winit.workspace = true
env_logger.workspace = true
log.workspace = true
