[package]
name = "spark-renderer"
version.workspace = true
edition.workspace = true

[dependencies]
spark-math = { path = "../spark-math" }
ash.workspace = true
shaderc.workspace = true
thiserror.workspace = true
ash-window.workspace = true
raw-window-handle.workspace = true
log.workspace = true
winit.workspace = true
egui.workspace = true
egui-ash.workspace = true
bytemuck.workspace = true
image.workspace = true
rayon.workspace = true
num_cpus.workspace = true
rand = "0.8"
