[package]
name = "spark-core"
version.workspace = true
edition.workspace = true

[dependencies]
spark-math = { path = "../spark-math" }
spark-renderer = { path = "../spark-renderer" }
winit.workspace = true
log.workspace = true
slotmap.workspace = true
thiserror.workspace = true
rayon.workspace = true
num_cpus.workspace = true
instant.workspace = true
image.workspace = true
gltf.workspace = true
